<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\LeituraArquivoService.cs" />
    <Compile Remove="Services\LeituraArquivoFactory.cs" />
    <Compile Remove="Services\ArquivoProjetoService.cs" />
    <Compile Remove="Services\ExportadorDxfService.cs" />
    <Compile Remove="Services\ExportarTxtService.cs" />
    <Compile Remove="Services\Leitores\**\*.cs" />
  </ItemGroup>

</Project>
